trigger:
- main

pool:
  name: Terraform

stages:

# ---------------- PLAN ----------------
- stage: Plan
  jobs:
  - job: TerraformPlan
    displayName: "Terraform Plan"
    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: "Terraform Install"
      inputs:
        terraformVersion: '1.9.5'

    - script: terraform fmt -check
      displayName: "Terraform Format Check"
      workingDirectory: '$(System.DefaultWorkingDirectory)/sandbox'

    - task: TerraformTaskV4@4
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/sandbox'
        backendServiceArm: 'terraform'
        backendAzureRmResourceGroupName: 'rg-sandbox'
        backendAzureRmStorageAccountName: 'stsandbox8754637487'
        backendAzureRmContainerName: 'terraformbackend'
        backendAzureRmKey: 'sandbox/terraform.tfstate'

    - task: TerraformTaskV4@4
      displayName: "Terraform Validate"
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/sandbox'

    # - task: TerraformTaskV4@4
    #   displayName: "Terraform Plan"
    #   name: planStep
    #   inputs:
    #     provider: 'azurerm'
    #     command: 'plan'
    #     workingDirectory: '$(System.DefaultWorkingDirectory)/sandbox'
    #     commandOptions: '-out=$(Pipeline.Workspace)/tfplan -detailed-exitcode'
    #     environmentServiceNameAzureRM: 'terraform'

    - task: AzureCLI@3
      inputs:
        connectionType: 'azureRM'
        azureSubscription: 'terraform'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'echo "Logged into Azure"'

    - bash: |
        terraform plan -out=$(Pipeline.Workspace)/tfplan -detailed-exitcode
        EXIT_CODE=$?

        echo "Exit code: $EXIT_CODE"

        if [ $EXIT_CODE -eq 1 ]; then
          echo "Terraform plan failed"
          exit 1
        fi

        echo "##vso[task.setvariable variable=tfPlanExitCode;isOutput=true]$EXIT_CODE"
      name: planStep
      displayName: "Terraform Plan (with exit code)"
      workingDirectory: '$(System.DefaultWorkingDirectory)/sandbox'

    - task: TerraformTaskV4@4
      displayName: "Terraform Show tfplan"
      inputs:
        provider: 'azurerm'
        command: 'show'
        workingDirectory: '$(System.DefaultWorkingDirectory)/sandbox'
        commandOptions: '$(Pipeline.Workspace)/tfplan'
        outputTo: 'console'
        outputFormat: 'default'
        environmentServiceNameAzureRM: 'terraform'

    - task: PublishPipelineArtifact@1
      displayName: "Upload Terraform Plan"
      inputs:
        targetPath: '$(Pipeline.Workspace)/tfplan'
        artifact: 'terraformplan'
        publishLocation: 'pipeline'

# ---------------- APPLY ----------------
- stage: Apply
  dependsOn: Plan
  condition: eq(dependencies.Plan.outputs['TerraformPlan.planStep.tfPlanExitCode'], '2')
  jobs:
  - deployment: TerraformApply
    environment: sandbox
    strategy:
      runOnce:
        deploy:
          steps:

          - task: DownloadPipelineArtifact@2
            displayName: "Download Terraform Plan"
            inputs:
              buildType: 'current'
              artifactName: 'terraformplan'
              targetPath: '$(Pipeline.Workspace)/artifacts'

          - task: TerraformInstaller@1
            displayName: "Terraform Install"
            inputs:
              terraformVersion: '1.9.5'

          - task: TerraformTaskV4@4
            displayName: "Terraform Apply"
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/sandbox'
              commandOptions: '$(Pipeline.Workspace)/artifacts/tfplan'
              environmentServiceNameAzureRM: 'terraform'
